default:
  image: python:3.10-slim-buster
  before_script:
    - apt-get update && apt-get install make

stages:
  - linters

run_linters:
  stage: linters
  before_script:
    - apt-get install -y --no-install-recommends git
    - pip install -r requirements.dev.txt
    - pre-commit install-hooks
    - pre-commit install
  script:
    - make linters
