stages:
  - linters

run_linters:
  stage: linters
  image: python:3.10-slim-buster
  before_script:
#    - apt update && apt install -y --no-install-recommends git
    - pip install -r requirements.dev.txt
    - pre-commit install-hooks
    - pre-commit install
  script:
    - make linters
