stages:
  - linters
  - deploy

variables:
  GIT_DEPTH: 0
  DATABASE_URL: $DATABASE_URL

run_linters:
  image: python:3.10-slim-buster
  stage: linters
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - apt-get update && apt-get install make && apt-get install -y git
    - pip install -r requirements.dev.txt
    - pre-commit install-hooks
    - pre-commit install
  script:
    - pre-commit run -a

deploy_dev:
  stage: deploy
  image: dokku/ci-docker-image
  only:
    - dev-add-deployment  # todo: change to dev
  environment:
    name: dev
  variables:
    GIT_REMOTE_URL: ssh://dokku@35.206.107.72:22/api-dev
  script:
    - dokku-deploy
  after_script: [dokku-unlock]
