stages:
#  - linters  todo: uncomment
  - deploy

variables:
  GIT_DEPTH: 0
  DATABASE_URL: $DATABASE_URL

#run_linters:
#  image: python:3.10-slim-buster
#  stage: linters
#  before_script:
#    - apt-get update && apt-get install make && apt-get install -y git
#    - pip install -r requirements.dev.txt
#    - pre-commit install-hooks
#    - pre-commit install
#  script:
#    - pre-commit run -a

deploy:
  stage: deploy
  image: dokku/ci-docker-image
  only:
    - dev-add-deployment  # todo: change to dev
  variables:
    GIT_REMOTE_URL: ssh://dokku@35.206.107.72:22/api-dev
    DATABASE_URL_2: $DATABASE_URL
  before_script:
    - echo "DATABASE_URL is $DATABASE_URL and DATABASE_URL_2 is $DATABASE_URL_2"
    - echo "DATABASE_URL=$DATABASE_URL" > .env
  script: dokku-deploy
  after_script: [dokku-unlock]
