version: '3.7'

services:
  db:
    container_name: covirally_postgres_test
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
