"""add tasks comments

Revision ID: 095f30776f38
Revises: c58542775dfb
Create Date: 2023-03-14 09:31:06.304838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095f30776f38'
down_revision = 'c58542775dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_comments',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::varchar'), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('edited', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_comments')
    # ### end Alembic commands ###
