"""add tasks table

Revision ID: 09952048a14d
Revises: c58901aaa5e2
Create Date: 2023-02-24 14:00:36.387012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09952048a14d'
down_revision = 'c58901aaa5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::varchar'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('due_to_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IDEA', 'IN_PROGRESS', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('suggested_by_id', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suggested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('tasks')
    op.execute("""DROP TYPE taskstatus""")
