"""remove phone number from users

Revision ID: 99c7fb046938
Revises: fbc920420a2b
Create Date: 2023-02-23 17:41:32.926875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c7fb046938'
down_revision = 'fbc920420a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone_number', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
