"""Changeded grades table

Revision ID: af09e7ee672d
Revises: 12231538492a
Create Date: 2023-03-22 22:53:32.928879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af09e7ee672d'
down_revision = '12231538492a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('grade_variant_int', sa.Integer(), nullable=False))
    op.add_column('grades', sa.Column('grade_rights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'grade_rights')
    op.drop_column('grades', 'grade_variant_int')
    # ### end Alembic commands ###
