"""Added grades table

Revision ID: be2ec4616665
Revises: c58542775dfb
Create Date: 2023-03-14 23:30:59.157320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2ec4616665'
down_revision = 'c58542775dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::varchar'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('grade_variant', sa.Enum('SUBSCRIBED', 'PAYED_POST', 'PAYED_SUBSCRIBED', 'TEAM_CREATOR', 'IS_CREATOR', name='grade_variant'), nullable=False),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('degrades_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_creator_id'), 'grades', ['creator_id'], unique=False)
    op.create_index(op.f('ix_grades_task'), 'grades', ['task'], unique=False)
    op.create_index(op.f('ix_grades_user_id'), 'grades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_user_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_task'), table_name='grades')
    op.drop_index(op.f('ix_grades_creator_id'), table_name='grades')
    op.drop_table('grades')
    # ### end Alembic commands ###
