"""add hashtag table

Revision ID: c58542775dfb
Revises: d4eb0ccf960e
Create Date: 2023-03-08 09:01:31.163120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58542775dfb'
down_revision = 'd4eb0ccf960e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::varchar'), nullable=False),
    sa.Column('hashtag', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_task_id'), 'hashtags', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hashtags_task_id'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
